owner: Clicki-Digital
repo: uptime
delay: 2000
skipDeleteIssues: true

sites:
  - name: Adam Brand Music
    url: https://adambrandmusic.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: All Access Electrical
    url: https://allaccesselectrical.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Ausource International
    url: https://ausourceintl.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Australian Anti Ice Campaign
    url: https://australianantiicecampaign.org.au
    expectedStatusCodes:
      - 0
      - 200
      - 201
    maxResponseTime: 30000
  - name: Beulah Revival Network
    url: https://beulah.net.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Bookkeeper to the Smart People
    url: https://bksp.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Burdi
    url: https://burdi.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Burdi - Selfservice
    url: https://manage.burdi.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Cafe7
    url: https://cafe7.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: CC Electrical and Air 
    url: https://ccelectricalandair.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Chariots of Light Australia 
    url: https://chariotsoflight.org.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: ClaimsWrights
    url: https://claimswrights.co.uk
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Clear Cut Seafood Training
    url: https://clearcutseafoodtraining.com/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  # - name: Clare Page Photography
    # url: https://clarepagephotography.com/
    # maxResponseTime: 30000
    # expectedStatusCodes:
    #   - 0
    #   - 200
    #   - 201
  - name: Clicki Digital
    url: https://clickidigital.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Contreat
    url: https://contreat.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Col Stringer
    url: https://colstringer.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Construction Training Institute
    url: https://cti.edu.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Diverse AirCon & Mechanical
    url: https://diverseaircon.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: EntVenture
    url: https://entventure.org
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Envirometal / We Buuy Scrap
    url: https://webuyscrap.com.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: First Harvest Coffee
    url: https://firstharvestcoffee.com.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Gary Rucci
    url: https://garyrucci.com/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Gracious5
    url: https://gracious5.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Gold Coast Edge Protection
    url: https://gcep.net.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Heritage of Faith Christian Church - Gold Coast
    url: https://heritageoffaith.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: HopeAlley
    url: https://hopealley.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: HopeAlley Ecards
    url: https://hopealley.com/ecards
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Hopelands Church
    url: https://hopelands.church
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Ian Slack
    url: https://ianslack.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Independent Wealth Management Australia
    url: https://iwmaus.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Jerry Savelle Ministries International Australia
    url: https://jsmiaustralia.org
    maxResponseTime: 7500
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Portal - Jerry Savelle Ministries International Australia
    url: https://portal.jsmiaustralia.org
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Keystone Leadership Group
    url: https://keystoneleadership.com.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Lance N. Solomon
    url: https://lancensolomon.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Lil Fi
    url: https://lilfi.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Little Groovers Dance Co
    url: https://littlegrooversdanceco.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Living Word Church
    url: https://livingword.org.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Lee Meehan Roofing
    url: https://lmr.net.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Legal Insite
    url: https://legalinsite.com.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Lounge Repair Guys
    url: https://loungerepairguys.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: LT Consulting
    url: https://ltconsulting.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Lucid Solutions
    url: https://getlucid.solutions
    icon: https://getlucid.solutions/wp-content/uploads/2020/12/cropped-ls-icon-32x32.png
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: The Lucid Group
    url: https://thelucid.group
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Minds and Hearts
    url: https://mindsandhearts.net
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Moncai
    url: https://moncai.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: NicNax
    url: https://nicnax.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Nyarima
    url: https://nyarima.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Nyarima
    url: https://nyarima.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Oasis House
    url: https://oasishouse.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Omega Communication Services
    url: https://omegacoms.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Optimise BnB
    url: https://optimisebnb.com.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Peak Horizons
    url: https://peakhorizons.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: RAC Equipment
    url: https://racequipment.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Stone Creative Group
    url: https://www.stonecreative.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Swell Plumbing and Gas
    url: https://swellplumbingandgas.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Tracy Hitchings Music
    url: https://tracyhitchingsmusic.com
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: VetAnswers
    url: https://vetanswers.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: VetMe
    url: https://www.vetme.com.au/
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  # - name: Waves Concrete Pumping
  #   url: https://wavesconcretepumping.com.au
  #   maxResponseTime: 30000
  #   expectedStatusCodes:
  #     - 0
  #     - 200
  #     - 201
  - name: Woman of Courage
    url: https://womenofcourageaustralia.com.au
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Worship Ministries International
    url: https://worshipministriesinternational.com	
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Young Discoverers
    url: https://youngdiscoverers.org.au	
    maxResponseTime: 30000
    expectedStatusCodes:
      - 0
      - 200
      - 201
    



status-website:
  theme: light
  cname: status.clicki.digital
  #baseUrl: /uptime
  logoUrl: https://clickidigital.com.au/wp-content/uploads/2021/02/ClickiDigital-horizontal-logo-FullColor.png
  name: Uptime Status
  introTitle: "**Clicki Digital** web hosting status"
  introMessage: "This status page provides *real-time* updates for the below listed sites that are managed by the Clicki Digital Infrastructure as a Service (IaaS) solution.
  <br>Clicki Digital utilises this tool to assist with unplanned outages."
  navbar:
    - title: Status
      href: /
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 9 * * *"
    staticSite: "10 * * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
