owner: Clicki-Digital
repo: uptime

sites:
  - name: Lucid Solutions
    url: https://getlucid.solutions
    icon: https://getlucid.solutions/wp-content/uploads/2020/12/cropped-ls-icon-32x32.png
  - name: Clicki Digital
    url: https://clickidigital.com.au
  - name: Heritage of Faith Christian Church - Gold Coast
    url: https://heritageoffaith.com.au
  - name: Jerry Savelle Ministries International Australia
    url: https://jsmiaustralia.org
  - name: Adam Brand Music
    url: https://adambrandmusic.com
  - name: Ausource International
    url: https://ausourceintl.com.au
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.clicki.digital
  baseUrl: /uptime
  logoUrl: https://getlucid.solutions/wp-content/uploads/2021/01/LS-logo.png
  name: Upptime
  introTitle: "**Lucid Solutions** web hosting status
  introMessage: This status page provides *real-time* updates for the below listed sites that are managed by Lucid Solutions and Clicki Digital.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
