owner: Clicki-Digital
repo: uptime
delay: 7000
skipDeleteIssues: true

defaults:
  method: GET
  headers:
    User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"

sites:
  - name: Adam Brand Music
    url: https://adambrandmusic.com
  - name: All Access Electrical
    url: https://allaccesselectrical.com.au
  - name: Ausource International
    url: https://ausourceintl.com.au
  - name: Australian Anti Ice Campaign
    url: https://australianantiicecampaign.org.au
  - name: Beulah Revival Network
    url: https://beulah.net.au
  - name: Bookkeeper to the Smart People
    url: https://bksp.com.au
  - name: Burdi
    url: https://burdi.com.au
  - name: Burdi - Selfservice
    url: https://manage.burdi.com.au
  - name: Cafe7
    url: https://cafe7.com.au
  - name: CC Electrical and Air
    url: https://ccelectricalandair.com.au
  - name: Chariots of Light Australia
    url: https://chariotsoflight.org.au
  - name: ClaimsWrights
    url: https://claimswrights.co.uk
  - name: Clear Cut Seafood Training
    url: https://clearcutseafoodtraining.com
  - name: Clicki Digital
    url: https://clickidigital.com.au
  - name: Contreat
    url: https://contreat.com.au
  - name: Col Stringer
    url: https://colstringer.com
  - name: Construction Training Institute
    url: https://cti.edu.au
  - name: Diverse AirCon & Mechanical
    url: https://diverseaircon.com.au
  - name: Envirometal / We Buuy Scrap
    url: https://webuyscrap.com.au
  - name: First Harvest Coffee
    url: https://firstharvestcoffee.com.au
  - name: Gary Rucci
    url: https://garyrucci.com
  - name: Gold Coast Edge Protection
    url: https://gcep.net.au
  - name: Heritage of Faith Christian Church - Gold Coast
    url: https://heritageoffaith.com.au
  - name: HopeAlley
    url: https://hopealley.com
  - name: HopeAlley Ecards
    url: https://hopealley.com/ecards
  - name: Hopelands Church
    url: https://hopelands.church
  - name: Ian Slack
    url: https://ianslack.com.au
  - name: Independent Wealth Management Australia
    url: https://iwmaus.com.au
  - name: Jerry Savelle Ministries International Australia
    url: https://jsmiaustralia.org
  - name: Portal - Jerry Savelle Ministries International Australia
    url: https://portal.jsmiaustralia.org
  - name: Keystone Leadership Group
    url: https://keystoneleadership.com.au
  - name: Lance N. Solomon
    url: https://lancensolomon.com.au
  - name: Lil Fi
    url: https://lilfi.com
  - name: Little Groovers Dance Co
    url: https://littlegrooversdanceco.com
  - name: Living Word Church
    url: https://livingword.org.au
  - name: Lee Meehan Roofing
    url: https://lmr.net.au
  - name: Legal Insite
    url: https://legalinsite.com.au
  - name: Lounge Repair Guys
    url: https://loungerepairguys.com.au
  - name: LT Consulting
    url: https://ltconsulting.com.au
  - name: Lucid Solutions
    url: https://getlucid.solutions
  - name: The Lucid Group
    url: https://thelucid.group
  - name: Minds and Hearts
    url: https://mindsandhearts.net
  - name: Moncai
    url: https://moncai.com.au
  - name: NicNax
    url: https://nicnax.com.au
  - name: Nyarima
    url: https://nyarima.com.au
  - name: Oasis House
    url: https://oasishouse.com.au
  - name: Omega Communication Services
    url: https://omegacoms.com.au
  - name: Optimise BnB
    url: https://optimisebnb.com.au
  - name: Peak Horizons
    url: https://peakhorizons.com.au
  - name: RAC Equipment
    url: https://racequipment.com.au
  - name: Stone Creative Group
    url: https://www.stonecreative.com.au
  - name: Swell Plumbing and Gas
    url: https://swellplumbingandgas.com.au
  - name: Tracy Hitchings Music
    url: https://tracyhitchingsmusic.com
  - name: VetAnswers
    url: https://vetanswers.com.au
  - name: VetMe
    url: https://www.vetme.com.au
  - name: Woman of Courage
    url: https://womenofcourageaustralia.com.au
  - name: Worship Ministries International
    url: https://worshipministriesinternational.com
  - name: Young Discoverers
    url: https://youngdiscoverers.org.au

status-website:
  theme: light
  cname: status.clicki.digital
  logoUrl: https://clickidigital.com.au/wp-content/uploads/2021/02/ClickiDigital-horizontal-logo-FullColor.png
  name: Uptime Status
  introTitle: "**Clicki Digital** web hosting status"
  introMessage: "This status page provides real-time updates for sites managed by the Clicki Digital Infrastructure as a Service (IaaS) solution.<br>Clicki Digital utilises this tool to assist with unplanned outages."
  navbar:
    - title: Status
      href: /
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 9 * * *"
    staticSite: "10 * * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"